repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.81.0
    hooks:
      - id: terraform_docs
        stages: [manual]

  - repo: local
    hooks:
      - id: terraform_docs-all
        name: terraform_docs
        entry: terraform
        language: system
        types: [file]
        files: .*
        pass_filenames: false
        stages: [manual]
